### ISSUE TITLE
String index out of range: 1 (500)

### ISSUE THREAD

**Issue by plamarque** [exo-addons/outlook#5]
When converting a message to an activity, most of the time, it fails in error. with : this message
String index out of range: 1 (500)

<img width="918" alt="screen shot 2016-11-18 at 20 09 22" src="https://cloud.githubusercontent.com/assets/227828/20442969/2998285a-adcb-11e6-92f5-f7bad7eb9b03.png">

**Comment by pnedonosko** [comment]
Server exception related this problem comes from WebUI CSS logic invoked by a listener on posting activity:
```
2016-11-18 15:16:58,674 | ERROR | Error converting message to activity status for plamarque@exoplatform.com [org.exoplatform.outlook.portlet.Outlook<http-nio-127.0.0.1-10180-exec-52>] 
java.lang.StringIndexOutOfBoundsException: String index out of range: 1
	at java.lang.String.substring(String.java:1963) ~[na:1.8.0_66]
	at org.exoplatform.webui.cssfile.CssClassManager.getCSSClassByFileName(CssClassManager.java:136) ~[commons-webui-component-4.4.0-M23.jar:4.4.0-M23]
	at org.exoplatform.webui.cssfile.CssClassUtils.getCSSClassByFileName(CssClassUtils.java:32) ~[commons-webui-component-4.4.0-M23.jar:4.4.0-M23]
	at org.exoplatform.webui.cssfile.CssClassUtils.getCSSClassByFileNameAndFileType(CssClassUtils.java:36) ~[commons-webui-component-4.4.0-M23.jar:4.4.0-M23]
	at org.exoplatform.wcm.ext.component.activity.listener.Utils.getDefaultThumbnailUrl(Utils.java:200) ~[integ-ecms-social-4.4.0-M23.jar:4.4.0-M23]
	at org.exoplatform.wcm.ext.component.activity.listener.Utils.populateActivityData(Utils.java:193) ~[integ-ecms-social-4.4.0-M23.jar:4.4.0-M23]
	at org.exoplatform.wcm.ext.component.activity.listener.Utils.createActivity(Utils.java:757) ~[integ-ecms-social-4.4.0-M23.jar:4.4.0-M23]
	at org.exoplatform.wcm.ext.component.activity.listener.Utils.postFileActivity(Utils.java:487) ~[integ-ecms-social-4.4.0-M23.jar:4.4.0-M23]
	at org.exoplatform.outlook.OutlookServiceImpl$OutlookSpaceImpl.postActivity(OutlookServiceImpl.java:658) ~[exo-outlook-services-1.0.0-RC1.jar:1.0.0-RC1]
	at org.exoplatform.outlook.portlet.Outlook.convertToStatus(Outlook.java:862) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
	at juzu.impl.request.Stage$Invoke.response(Stage.java:385) ~[juzu-core-1.1.3.jar:na]
	at juzu.impl.request.Stage.invoke(Stage.java:90) [juzu-core-1.1.3.jar:na]
	at juzu.impl.request.Stage$LifeCycle.response(Stage.java:325) ~[juzu-core-1.1.3.jar:na]
	at juzu.impl.request.Stage.invoke(Stage.java:90) [juzu-core-1.1.3.jar:na]
	at juzu.impl.request.Stage$Handler.response(Stage.java:278) [juzu-core-1.1.3.jar:na]
	at juzu.impl.request.Stage.invoke(Stage.java:90) [juzu-core-1.1.3.jar:na]
	at juzu.impl.request.Stage$Unmarshalling.response(Stage.java:158) [juzu-core-1.1.3.jar:na]
	at juzu.impl.request.Stage.invoke(Stage.java:90) [juzu-core-1.1.3.jar:na]
	at org.exoplatform.commons.juzu.ajax.AjaxService.handle(AjaxService.java:81) [commons-juzu-4.4.0-M23.jar:4.4.0-M23]
	at org.exoplatform.commons.juzu.ajax.AjaxService.handle(AjaxService.java:41) [commons-juzu-4.4.0-M23.jar:4.4.0-M23]
	at juzu.impl.request.Stage.invoke(Stage.java:83) [juzu-core-1.1.3.jar:na]
	at juzu.impl.plugin.asset.AssetService.handle(AssetService.java:283) [juzu-core-1.1.3.jar:na]
	at juzu.impl.plugin.asset.AssetService.handle(AssetService.java:52) [juzu-core-1.1.3.jar:na]
	at juzu.impl.request.Stage.invoke(Stage.java:83) [juzu-core-1.1.3.jar:na]
	at juzu.impl.request.Request.invoke(Request.java:194) [juzu-core-1.1.3.jar:na]
	at juzu.impl.plugin.controller.ControllerService.invoke(ControllerService.java:156) [juzu-core-1.1.3.jar:na]
	at juzu.impl.bridge.spi.portlet.PortletRequestBridge.invoke(PortletRequestBridge.java:311) [juzu-core-1.1.3.jar:na]
	at juzu.bridge.portlet.JuzuPortlet.serveResource(JuzuPortlet.java:365) [juzu-core-1.1.3.jar:na]
	at org.gatein.pc.portlet.impl.jsr168.PortletContainerImpl$Invoker.doFilter(PortletContainerImpl.java:598) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.gatein.pc.portlet.impl.jsr168.api.FilterChainImpl.doFilter(FilterChainImpl.java:184) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.exoplatform.portal.application.ApplicationMonitoringFilter.doFilter(ApplicationMonitoringFilter.java:76) [exo.portal.webui.portal-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.gatein.pc.portlet.impl.jsr168.api.FilterChainImpl.doFilter(FilterChainImpl.java:184) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.gatein.pc.portlet.impl.jsr168.api.FilterChainImpl.doFilter(FilterChainImpl.java:84) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.gatein.pc.portlet.impl.jsr168.PortletContainerImpl.dispatch(PortletContainerImpl.java:529) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.gatein.pc.portlet.container.ContainerPortletDispatcher.invoke(ContainerPortletDispatcher.java:42) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.gatein.pc.portlet.PortletInvokerInterceptor.invoke(PortletInvokerInterceptor.java:111) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.gatein.pc.portlet.aspects.EventPayloadInterceptor.invoke(EventPayloadInterceptor.java:197) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.gatein.pc.portlet.PortletInvokerInterceptor.invoke(PortletInvokerInterceptor.java:111) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.gatein.pc.portlet.aspects.RequestAttributeConversationInterceptor.invoke(RequestAttributeConversationInterceptor.java:119) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.gatein.pc.portlet.PortletInvokerInterceptor.invoke(PortletInvokerInterceptor.java:111) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.gatein.pc.portlet.aspects.CCPPInterceptor.invoke(CCPPInterceptor.java:65) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.gatein.pc.portlet.PortletInvokerInterceptor.invoke(PortletInvokerInterceptor.java:111) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.gatein.pc.bridge.BridgeInterceptor.invoke(BridgeInterceptor.java:49) [pc-bridge-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.gatein.pc.portlet.PortletInvokerInterceptor.invoke(PortletInvokerInterceptor.java:111) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.gatein.pc.portlet.PortletInvokerInterceptor.invoke(PortletInvokerInterceptor.java:111) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.gatein.pc.portlet.aspects.SessionInvalidatorInterceptor.invoke(SessionInvalidatorInterceptor.java:55) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.gatein.pc.portlet.PortletInvokerInterceptor.invoke(PortletInvokerInterceptor.java:111) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.gatein.pc.portlet.aspects.ContextDispatcherInterceptor.access$201(ContextDispatcherInterceptor.java:46) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.gatein.pc.portlet.aspects.ContextDispatcherInterceptor$CallableImpl.call(ContextDispatcherInterceptor.java:119) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.exoplatform.portal.webui.application.ExoServerContext$1.doCallback(ExoServerContext.java:49) [exo.portal.webui.portal-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.gatein.wci.command.CommandDispatcher$CallbackCommand.execute(CommandDispatcher.java:82) [wci-wci-2.4.1.Final.jar:2.4.1.Final]
	at org.gatein.wci.command.TomcatCommandDispatcher$1.execute(TomcatCommandDispatcher.java:61) [wci-tomcat7-2.4.1.Final.jar:2.4.1.Final]
	at sun.reflect.GeneratedMethodAccessor699.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
	at org.gatein.wci.command.CommandServlet.doGet(CommandServlet.java:135) [wci-wci-2.4.1.Final.jar:2.4.1.Final]
	at org.gatein.wci.command.CommandServlet.doPost(CommandServlet.java:166) [wci-wci-2.4.1.Final.jar:2.4.1.Final]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650) [servlet-api.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731) [servlet-api.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [catalina.jar:7.0.70]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.70]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:747) [catalina.jar:7.0.70]
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:603) [catalina.jar:7.0.70]
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:542) [catalina.jar:7.0.70]
	at org.gatein.wci.command.CommandServlet.include(CommandServlet.java:84) [wci-wci-2.4.1.Final.jar:2.4.1.Final]
	at org.gatein.wci.command.TomcatCommandDispatcher.include(TomcatCommandDispatcher.java:97) [wci-tomcat7-2.4.1.Final.jar:2.4.1.Final]
	at org.gatein.wci.tomcat.TC7ServletContainerContext.include(TC7ServletContainerContext.java:113) [wci-tomcat7-2.4.1.Final.jar:2.4.1.Final]
	at org.gatein.wci.ServletContainer.include(ServletContainer.java:395) [wci-wci-2.4.1.Final.jar:2.4.1.Final]
	at org.exoplatform.portal.webui.application.ExoServerContext.dispatch(ExoServerContext.java:45) [exo.portal.webui.portal-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.gatein.pc.portlet.aspects.ContextDispatcherInterceptor.invoke(ContextDispatcherInterceptor.java:65) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.gatein.pc.portlet.PortletInvokerInterceptor.invoke(PortletInvokerInterceptor.java:111) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.exoplatform.portal.pc.aspects.PortletLifecyclePhaseInterceptor.invoke(PortletLifecyclePhaseInterceptor.java:30) [exo.portal.component.pc-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.gatein.pc.portlet.PortletInvokerInterceptor.invoke(PortletInvokerInterceptor.java:111) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.gatein.pc.portlet.aspects.SecureTransportInterceptor.invoke(SecureTransportInterceptor.java:69) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.gatein.pc.portlet.PortletInvokerInterceptor.invoke(PortletInvokerInterceptor.java:111) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.gatein.pc.portlet.aspects.ValveInterceptor.invoke(ValveInterceptor.java:84) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.gatein.pc.portlet.PortletInvokerInterceptor.invoke(PortletInvokerInterceptor.java:111) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.gatein.pc.portlet.container.ContainerPortletInvoker.invoke(ContainerPortletInvoker.java:130) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.gatein.pc.portlet.PortletInvokerInterceptor.invoke(PortletInvokerInterceptor.java:111) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.gatein.pc.portlet.state.producer.ProducerPortletInvoker.invoke(ProducerPortletInvoker.java:263) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.gatein.pc.federation.impl.FederatedPortletInvokerService.invoke(FederatedPortletInvokerService.java:163) [pc-federation-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.gatein.pc.federation.impl.FederatingPortletInvokerService.invoke(FederatingPortletInvokerService.java:246) [pc-federation-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.gatein.pc.portlet.PortletInvokerInterceptor.invoke(PortletInvokerInterceptor.java:111) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.gatein.pc.portlet.aspects.PortletCustomizationInterceptor.invoke(PortletCustomizationInterceptor.java:76) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.gatein.pc.portlet.PortletInvokerInterceptor.invoke(PortletInvokerInterceptor.java:111) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.gatein.pc.portlet.aspects.ConsumerCacheInterceptor.invoke(ConsumerCacheInterceptor.java:247) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.gatein.pc.portlet.PortletInvokerInterceptor.invoke(PortletInvokerInterceptor.java:111) [pc-portlet-2.6.0-M01-PLF.jar:2.6.0-M01-PLF]
	at org.exoplatform.portal.webui.application.UIPortlet.invoke(UIPortlet.java:1012) [exo.portal.webui.portal-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.exoplatform.portal.webui.application.UIPortletActionListener$ServeResourceActionListener.execute(UIPortletActionListener.java:341) [exo.portal.webui.portal-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.exoplatform.webui.event.Event.broadcast(Event.java:97) [exo.portal.webui.framework-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.exoplatform.portal.webui.application.UIPortletLifecycle.processAction(UIPortletLifecycle.java:119) [exo.portal.webui.portal-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.exoplatform.portal.webui.application.UIPortletLifecycle.processAction(UIPortletLifecycle.java:58) [exo.portal.webui.portal-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.exoplatform.webui.core.UIComponent.processAction(UIComponent.java:120) [exo.portal.webui.framework-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.exoplatform.portal.webui.workspace.UIPortalApplicationLifecycle.processAction(UIPortalApplicationLifecycle.java:73) [exo.portal.webui.portal-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.exoplatform.portal.webui.workspace.UIPortalApplicationLifecycle.processAction(UIPortalApplicationLifecycle.java:36) [exo.portal.webui.portal-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.exoplatform.webui.core.UIComponent.processAction(UIComponent.java:120) [exo.portal.webui.framework-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.exoplatform.webui.core.UIApplication.processAction(UIApplication.java:123) [exo.portal.webui.framework-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.exoplatform.portal.webui.workspace.UIPortalApplication.processAction(UIPortalApplication.java:789) [exo.portal.webui.portal-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.exoplatform.portal.application.PortalRequestHandler.processRequest(PortalRequestHandler.java:228) [exo.portal.webui.portal-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.exoplatform.portal.application.PortalRequestHandler.execute(PortalRequestHandler.java:184) [exo.portal.webui.portal-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.exoplatform.web.WebAppController.service(WebAppController.java:348) [exo.portal.component.web.controller-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.exoplatform.portal.application.PortalController.onService(PortalController.java:110) [exo.portal.webui.portal-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.exoplatform.container.web.AbstractHttpServlet.service(AbstractHttpServlet.java:133) [exo.kernel.container-2.6.0-M09.jar:2.6.0-M09]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731) [servlet-api.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [catalina.jar:7.0.70]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.70]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat7-websocket.jar:7.0.70]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.70]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.70]
	at org.exoplatform.web.filter.ExtensibleFilter$ExtensibleFilterChain.doFilter(ExtensibleFilter.java:96) [exo.portal.component.web.api-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.exoplatform.platform.common.account.setup.web.AccountSetupFilter.doFilter(AccountSetupFilter.java:60) [platform-component-common-4.4.0-M23.jar:4.4.0-M23]
	at org.exoplatform.web.filter.ExtensibleFilter$ExtensibleFilterChain.doFilter(ExtensibleFilter.java:92) [exo.portal.component.web.api-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.exoplatform.platform.common.software.register.web.SoftwareRegisterFilter.doFilter(SoftwareRegisterFilter.java:88) [platform-component-common-4.4.0-M23.jar:4.4.0-M23]
	at org.exoplatform.web.filter.ExtensibleFilter$ExtensibleFilterChain.doFilter(ExtensibleFilter.java:92) [exo.portal.component.web.api-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.exoplatform.platform.welcomescreens.web.TermsAndConditionsFilter.doFilter(TermsAndConditionsFilter.java:78) [platform-welcome-screens-component-4.4.0-M23.jar:4.4.0-M23]
	at org.exoplatform.web.filter.ExtensibleFilter$ExtensibleFilterChain.doFilter(ExtensibleFilter.java:92) [exo.portal.component.web.api-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.exoplatform.outlook.server.filter.OutlookRememberMeFilter.doFilter(OutlookRememberMeFilter.java:187) [exo-outlook-services-1.0.0-RC1.jar:1.0.0-RC1]
	at org.exoplatform.web.filter.ExtensibleFilter$ExtensibleFilterChain.doFilter(ExtensibleFilter.java:92) [exo.portal.component.web.api-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.exoplatform.outlook.webui.OutlookContextFilter.doFilter(OutlookContextFilter.java:65) [exo-outlook-services-1.0.0-RC1.jar:1.0.0-RC1]
	at org.exoplatform.web.filter.ExtensibleFilter$ExtensibleFilterChain.doFilter(ExtensibleFilter.java:92) [exo.portal.component.web.api-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.exoplatform.services.wcm.friendly.impl.FriendlyFilter.doFilter(FriendlyFilter.java:54) [ecms-core-services-4.4.0-M23.jar:4.4.0-M23]
	at org.exoplatform.web.filter.ExtensibleFilter$ExtensibleFilterChain.doFilter(ExtensibleFilter.java:92) [exo.portal.component.web.api-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.exoplatform.community.filter.ParamsFilter.doFilter(ParamsFilter.java:352) [exo-community-services-4.4.0-M23-W45.jar:4.4.0-M23-W45]
	at org.exoplatform.web.filter.ExtensibleFilter$ExtensibleFilterChain.doFilter(ExtensibleFilter.java:92) [exo.portal.component.web.api-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.exoplatform.community.common.OAuthRememberMeFilter.doFilter(OAuthRememberMeFilter.java:131) [exo-community-oauth-4.4.0-M23-W45.jar:4.4.0-M23-W45]
	at org.exoplatform.community.common.OAuthRememberMeFilter.doFilter(OAuthRememberMeFilter.java:50) [exo-community-oauth-4.4.0-M23-W45.jar:4.4.0-M23-W45]
	at org.exoplatform.web.filter.ExtensibleFilter$ExtensibleFilterChain.doFilter(ExtensibleFilter.java:92) [exo.portal.component.web.api-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.exoplatform.community.common.OAuthLogoutFilter.doFilter(OAuthLogoutFilter.java:81) [exo-community-oauth-4.4.0-M23-W45.jar:4.4.0-M23-W45]
	at org.exoplatform.web.filter.ExtensibleFilter$ExtensibleFilterChain.doFilter(ExtensibleFilter.java:92) [exo.portal.component.web.api-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.exoplatform.services.filters.sessionProvider.ThreadLocalACLSessionProviderInitializedFilter.doFilter(ThreadLocalACLSessionProviderInitializedFilter.java:45) [ecms-core-services-4.4.0-M23.jar:4.4.0-M23]
	at org.exoplatform.web.filter.ExtensibleFilter$ExtensibleFilterChain.doFilter(ExtensibleFilter.java:92) [exo.portal.component.web.api-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.gatein.portal.installer.PortalSetupFilter.doFilter(PortalSetupFilter.java:72) [exo.portal.component.web.api-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.exoplatform.web.filter.ExtensibleFilter$ExtensibleFilterChain.doFilter(ExtensibleFilter.java:92) [exo.portal.component.web.api-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.exoplatform.platform.common.software.register.UnlockService$UnlockFilter.doFilter(UnlockService.java:393) [platform-component-common-4.4.0-M23.jar:4.4.0-M23]
	at org.exoplatform.web.filter.ExtensibleFilter$ExtensibleFilterChain.doFilter(ExtensibleFilter.java:92) [exo.portal.component.web.api-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.exoplatform.oauth.filter.OAuthAbstractFilter.doFilter(OAuthAbstractFilter.java:60) [platform-component-oauth-auth-4.4.0-M23.jar:4.4.0-M23]
	at org.exoplatform.web.filter.ExtensibleFilter$ExtensibleFilterChain.doFilter(ExtensibleFilter.java:92) [exo.portal.component.web.api-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.exoplatform.web.filter.ExtensibleFilter.doFilter(ExtensibleFilter.java:71) [exo.portal.component.web.api-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.exoplatform.web.filter.GenericFilter.doFilter(GenericFilter.java:70) [exo.portal.component.web.api-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.70]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.70]
	at org.exoplatform.web.CacheUserProfileFilter.doFilter(CacheUserProfileFilter.java:73) [exo.portal.component.web.security-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.70]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.70]
	at org.exoplatform.frameworks.jcr.web.ThreadLocalSessionProviderInitializedFilter.doFilter(ThreadLocalSessionProviderInitializedFilter.java:122) [exo.jcr.framework.web-1.17.0-M11.jar:1.17.0-M11]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.70]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.70]
	at org.exoplatform.web.login.ConversationStateUpdateFilter.doFilter(ConversationStateUpdateFilter.java:66) [exo.portal.component.web.security-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.70]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.70]
	at org.exoplatform.services.security.web.SetCurrentIdentityFilter.doFilter(SetCurrentIdentityFilter.java:88) [exo.core.component.security.core-2.7.0-M09.jar:2.7.0-M09]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.70]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.70]
	at org.exoplatform.web.login.RememberMeFilter.doFilter(RememberMeFilter.java:135) [exo.portal.component.web.security-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.exoplatform.web.login.RememberMeFilter.doFilter(RememberMeFilter.java:57) [exo.portal.component.web.security-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.70]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.70]
	at org.gatein.security.oauth.webapi.OAuthDelegateFilter.doFilter(OAuthDelegateFilter.java:58) [exo.portal.component.web.oauth-web-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.70]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.70]
	at org.gatein.sso.integration.SSODelegateFilter.doFilter(SSODelegateFilter.java:60) [sso-integration-1.4.5.Final.jar:1.4.5.Final]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.70]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.70]
	at org.exoplatform.container.web.PortalContainerFilter.doFilter(PortalContainerFilter.java:78) [exo.kernel.container-2.6.0-M09.jar:2.6.0-M09]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.70]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.70]
	at org.gatein.portal.init.PortalCheckInitFilter.doFilter(PortalCheckInitFilter.java:66) [exo.portal.component.portal-4.4.0-M15-PLF.jar:4.4.0-M15-PLF]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.70]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.70]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218) [catalina.jar:7.0.70]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) [catalina.jar:7.0.70]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505) [catalina.jar:7.0.70]
	at org.gatein.sso.agent.tomcat.ServletAccessValve.invoke(ServletAccessValve.java:55) [sso-agent-1.4.5.Final.jar:1.4.5.Final]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169) [catalina.jar:7.0.70]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) [catalina.jar:7.0.70]
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:683) [catalina.jar:7.0.70]
	at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:321) [catalina.jar:7.0.70]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [catalina.jar:7.0.70]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:442) [catalina.jar:7.0.70]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1082) [tomcat-coyote.jar:7.0.70]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:623) [tomcat-coyote.jar:7.0.70]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1756) [tomcat-coyote.jar:7.0.70]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1715) [tomcat-coyote.jar:7.0.70]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_66]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-coyote.jar:7.0.70]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]
```

**Comment by pnedonosko** [comment]
This problem caused by https://jira.exoplatform.org/browse/COMMONS-510. To bypass it, we'll remove ending dots in message node names.

**Comment by pnedonosko** [comment]
Ending dot will be removed in JCR node name, but document title (exo:title) still will be like the original message subject.
